[build]
  publish = "packages/web/build"
  command = "cd packages/web && yarn build"

[build.environment]
  CI = "false"
  NODE_OPTIONS = "--max_old_space_size=4096"
  INLINE_RUNTIME_CHUNK = "false"
  NODE_VERSION = "14.15.0"
